[package]
name = "fractal-explorer"
version = "0.2.0"
authors = ["Simon Schneemelcher <s.schneemelcher@tu-bs.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.19.3"
num-complex = "0.4.0"
